apiVersion: apps/v1
kind: Deployment
metadata:
  name: marsel-demo-web
  namespace: NAMESPACE
  labels:
    app: marsel-demo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marsel-demo-web
  template:
    metadata:
      labels:
        app: marsel-demo-web
    spec:
      containers:
      - name: marsel-demo-web
        image: ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/webapp:IMAGEVERSION
        env:
          - name: PORT 
            value: "80"
          - name: API_HOST
            value: http://backend-api-svc:80
        ports:
        - containerPort: 80
